"""Alembic 迁移模板。

Revision ID: e51167fb8da7
Revises:
Create Date: 2026-07-15
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e51167fb8da7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('employee_no', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('source_employee_key', sa.String(length=200), nullable=True),
    sa.Column('employee_status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_employee_no'), ['employee_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('followup_node_definition',
    sa.Column('node_code', sa.String(length=50), nullable=False),
    sa.Column('node_name', sa.String(length=200), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('offset_days', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_assignee_rule', sa.String(length=200), nullable=True),
    sa.Column('confirmation_mode', sa.String(length=10), nullable=False),
    sa.Column('node_version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_code')
    )
    op.create_table('operation_log',
    sa.Column('operator_id', sa.String(length=100), nullable=False),
    sa.Column('operated_at', sa.DateTime(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('operation_source', sa.String(length=100), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_log_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_operated_at'), ['operated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_log_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_oplog_object', ['object_type', 'object_id'], unique=False)

    op.create_table('system_todo',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.Column('todo_status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('system_todo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_todo_user_id'), ['user_id'], unique=False)

    op.create_table('employment_record',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employment_seq', sa.Integer(), nullable=False),
    sa.Column('employment_status', sa.String(length=30), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('probation_start_date', sa.Date(), nullable=True),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('probation_status', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('manager_name', sa.String(length=100), nullable=True),
    sa.Column('regularization_date', sa.Date(), nullable=True),
    sa.Column('separation_date', sa.Date(), nullable=True),
    sa.Column('date_rule_source', sa.String(length=50), nullable=True),
    sa.Column('probation_end_date_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'employment_seq', name='uq_employee_seq')
    )
    with op.batch_alter_table('employment_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employment_record_employee_id'), ['employee_id'], unique=False)

    op.create_table('employment_change',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=30), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employment_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employment_change_employment_id'), ['employment_id'], unique=False)

    op.create_table('followup_task',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('node_definition_id', sa.Integer(), nullable=True),
    sa.Column('node_version', sa.Integer(), nullable=True),
    sa.Column('node_code_snapshot', sa.String(length=50), nullable=True),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('task_source', sa.String(length=10), nullable=False),
    sa.Column('trigger_type_snapshot', sa.String(length=50), nullable=True),
    sa.Column('offset_days_snapshot', sa.Integer(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('original_planned_date', sa.Date(), nullable=True),
    sa.Column('date_adjusted_manually', sa.Boolean(), nullable=False),
    sa.Column('followup_status', sa.String(length=30), nullable=False),
    sa.Column('confirmation_mode', sa.String(length=10), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.String(length=100), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_record.id'], ),
    sa.ForeignKeyConstraint(['node_definition_id'], ['followup_node_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('followup_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followup_task_employment_id'), ['employment_id'], unique=False)

    op.create_table('separation_record',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('planned_separation_date', sa.Date(), nullable=True),
    sa.Column('actual_separation_date', sa.Date(), nullable=True),
    sa.Column('separation_type', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('hr_comment', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('separation_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_separation_record_employment_id'), ['employment_id'], unique=False)

    op.create_table('communication_record',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('followup_task_id', sa.Integer(), nullable=True),
    sa.Column('communication_type', sa.String(length=50), nullable=True),
    sa.Column('communication_at', sa.DateTime(), nullable=True),
    sa.Column('hr_user_id', sa.String(length=100), nullable=True),
    sa.Column('communication_status', sa.String(length=30), nullable=False),
    sa.Column('current_text_version_id', sa.Integer(), nullable=True),
    sa.Column('current_text_version_no', sa.Integer(), nullable=True),
    sa.Column('current_text_hash', sa.String(length=64), nullable=True),
    sa.Column('manual_summary', sa.Text(), nullable=True),
    sa.Column('hr_conclusion', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_record.id'], ),
    sa.ForeignKeyConstraint(['followup_task_id'], ['followup_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communication_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_record_employment_id'), ['employment_id'], unique=False)

    op.create_table('followup_task_confirmation',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('confirmation_status', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['followup_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', 'request_id', name='uq_task_confirmation')
    )
    with op.batch_alter_table('followup_task_confirmation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followup_task_confirmation_task_id'), ['task_id'], unique=False)

    op.create_table('followup_task_participant',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('participant_role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['followup_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', name='uq_task_participant')
    )
    with op.batch_alter_table('followup_task_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followup_task_participant_task_id'), ['task_id'], unique=False)

    op.create_table('ai_summary_version',
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('source_text_version_id', sa.Integer(), nullable=True),
    sa.Column('source_text_version_no', sa.Integer(), nullable=True),
    sa.Column('source_text_hash', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_snapshot', sa.Text(), nullable=True),
    sa.Column('output_schema_version', sa.String(length=50), nullable=True),
    sa.Column('summary_status', sa.String(length=30), nullable=False),
    sa.Column('structured_summary', sa.Text(), nullable=True),
    sa.Column('raw_response_ref', sa.String(length=500), nullable=True),
    sa.Column('is_ai_suggestion', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('failure_type', sa.String(length=50), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication_record.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('communication_id', 'version_no', name='uq_ai_summary_version'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('ai_summary_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_summary_version_communication_id'), ['communication_id'], unique=False)

    op.create_table('communication_text_version',
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('text_length', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication_record.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('communication_id', 'version_no', name='uq_comm_text_version')
    )
    with op.batch_alter_table('communication_text_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_text_version_communication_id'), ['communication_id'], unique=False)

    op.create_table('probation_review',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('followup_task_id', sa.Integer(), nullable=True),
    sa.Column('communication_id', sa.Integer(), nullable=True),
    sa.Column('review_seq', sa.Integer(), nullable=False),
    sa.Column('review_stage', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=True),
    sa.Column('hr_evaluation', sa.Text(), nullable=True),
    sa.Column('employee_feedback', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communication_record.id'], ),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_record.id'], ),
    sa.ForeignKeyConstraint(['followup_task_id'], ['followup_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('probation_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_probation_review_employment_id'), ['employment_id'], unique=False)

    op.create_table('regularization_record',
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('probation_review_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('new_probation_end_date', sa.Date(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('ai_summary_version_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('is_effective', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['ai_summary_version_id'], ['ai_summary_version.id'], ),
    sa.ForeignKeyConstraint(['employment_id'], ['employment_record.id'], ),
    sa.ForeignKeyConstraint(['probation_review_id'], ['probation_review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regularization_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regularization_record_employment_id'), ['employment_id'], unique=False)

    op.create_table('risk_assessment',
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('source_text_version_id', sa.Integer(), nullable=True),
    sa.Column('ai_summary_version_id', sa.Integer(), nullable=True),
    sa.Column('assessment_source', sa.String(length=10), nullable=False),
    sa.Column('ai_risk_level', sa.String(length=20), nullable=True),
    sa.Column('ai_risk_reasons', sa.Text(), nullable=True),
    sa.Column('ai_evidence', sa.Text(), nullable=True),
    sa.Column('ai_followup_suggestions', sa.Text(), nullable=True),
    sa.Column('risk_review_status', sa.String(length=30), nullable=False),
    sa.Column('hr_risk_level', sa.String(length=20), nullable=True),
    sa.Column('hr_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['ai_summary_version_id'], ['ai_summary_version.id'], ),
    sa.ForeignKeyConstraint(['communication_id'], ['communication_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessment_communication_id'), ['communication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessment_communication_id'))

    op.drop_table('risk_assessment')
    with op.batch_alter_table('regularization_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regularization_record_employment_id'))

    op.drop_table('regularization_record')
    with op.batch_alter_table('probation_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_probation_review_employment_id'))

    op.drop_table('probation_review')
    with op.batch_alter_table('communication_text_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_text_version_communication_id'))

    op.drop_table('communication_text_version')
    with op.batch_alter_table('ai_summary_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_summary_version_communication_id'))

    op.drop_table('ai_summary_version')
    with op.batch_alter_table('followup_task_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followup_task_participant_task_id'))

    op.drop_table('followup_task_participant')
    with op.batch_alter_table('followup_task_confirmation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followup_task_confirmation_task_id'))

    op.drop_table('followup_task_confirmation')
    with op.batch_alter_table('communication_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_record_employment_id'))

    op.drop_table('communication_record')
    with op.batch_alter_table('separation_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_separation_record_employment_id'))

    op.drop_table('separation_record')
    with op.batch_alter_table('followup_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followup_task_employment_id'))

    op.drop_table('followup_task')
    with op.batch_alter_table('employment_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employment_change_employment_id'))

    op.drop_table('employment_change')
    with op.batch_alter_table('employment_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employment_record_employee_id'))

    op.drop_table('employment_record')
    with op.batch_alter_table('system_todo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_todo_user_id'))

    op.drop_table('system_todo')
    with op.batch_alter_table('operation_log', schema=None) as batch_op:
        batch_op.drop_index('ix_oplog_object')
        batch_op.drop_index(batch_op.f('ix_operation_log_request_id'))
        batch_op.drop_index(batch_op.f('ix_operation_log_operator_id'))
        batch_op.drop_index(batch_op.f('ix_operation_log_operated_at'))
        batch_op.drop_index(batch_op.f('ix_operation_log_business_id'))

    op.drop_table('operation_log')
    op.drop_table('followup_node_definition')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_employee_employee_no'))

    op.drop_table('employee')
    # ### end Alembic commands ###
